apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: js7joc
  name: js7joc
  namespace: js7
spec:
  volumes:
  - name: hibernate-config
    configMap:
        name: hibernate-config
  containers:
  - image: sosberlin/js7:joc-2-5-1
    name: js7joc
    ports:
    - containerPort: 4446
    volumeMounts:
    - name: hibernate-config
      mountPath: /var/sos-berlin.com/js7/joc/resources/joc/

    env:
    - name: RUN_JS_JAVA_OPTIONS
      value: "-Xmx256m"
    - name: RUN_JS_USER_ID
      value:  "0:0"

  - image: sosberlin/js7:controller-2-5-1
    name: js7con
    ports:
    - containerPort: 4444
    env:
    - name: RUN_JS_JAVA_OPTIONS
      value: "-Xmx256m"
    - name: RUN_JS_USER_ID
      value:  "0:0"
    - name: RUN_JS_ID
      value:  "jobscheduler"

  - image: sosberlin/js7:agent-2-5-1
    name: js7agent
    ports:
    - containerPort: 4445
    env:
    - name: RUN_JS_JAVA_OPTIONS
      value: "-Xmx256m"
    - name: RUN_JS_USER_ID
      value:  "0:0"
