---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cnpg/cloudnative-pg
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
      version: '0.21.*'
  interval: 1h0m0s
