apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-tests
spec:
  workspaces:
  - name: source
  steps:
  - name: run-tests
    image: python:3-slim-buster
    workingDir: $(workspaces.source.path)
    script: |
      #!/bin/bash
      set -e

      pip install --no-cache-dir --upgrade -r requirements.txt

      cat <<EOF > .env
      # [App]
      APP_TITLE="Hero App"
      APP_HOST="0.0.0.0"
      APP_PORT=8080
      APP_RELOAD=true
      APP_DEBUG=true

      # [Prefixes]
      PREFIX_PUBLIC="/public"
      PREFIX_ADMIN="/admin"

      # [PostgreSQL]
      POSTGRESQL_DSN="postgresql+asyncpg://hero:heroPass123@test-db.tekton-temp:5432/heroes_db"

      # [Security]
      SECURITY_API_KEY="7Xnky99uzTnfku1jRjKIRllVUKIQVlBkF3xfzicu26Y"
      EOF

      # alembic upgrade head

      coverage run -m pytest && coverage report -m
