apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-db
  name: test-db
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: test-db
  type: LoadBalancer
